### ISSUE TITLE
Add retry mechanism for hub scanner download

### ISSUE THREAD

**Issue by sheppduck** [blackducksoftware/perceptor-scanner#38]
In https://github.com/blackducksoftware/hub-client-go/commit/a5e3a47fc9bffe5f92467effa0ac65fde2ac77f9 I've bumped the timeout from 5 to 20 sec but the perceptor scanner keeps timing out at downloading the client:
E.g.
time="2018-03-12T21:27:24Z" level=info msg=started
time="2018-03-12T21:27:24Z" level=info msg="successfully instantiated hub client https://18.219.123.21"
time="2018-03-12T21:27:24Z" level=info msg="successfully logged in to hub"
time="2018-03-12T21:27:24Z" level=info msg="got hub version: 4.4.0"
time="2018-03-12T21:27:29Z" level=error msg="unable to download scan client: net/http: request canceled (Client.Timeout exceeded while reading body)"
time="2018-03-12T21:27:29Z" level=error msg="unable to download scan client: net/http: request canceled (Client.Timeout exceeded while reading body)"
time="2018-03-12T21:27:29Z" level=error msg="unable to instantiate scanner: net/http: request canceled (Client.Timeout exceeded while reading body)"
panic: net/http: request canceled (Client.Timeout exceeded while reading body)
 goroutine 1 [running]:
main.main()
	/workspace/gopath/src/github.com/blackducksoftware/perceptor-scanner/cmd/perceptor-scanner/perceptor-scanner.go:49 +0x41e

**Comment by mattfenwick** [comment]
Fixed by #39!

**Comment by mattfenwick** [comment]
My bad -- shouldn't have closed it -- reopening.

**Comment by mattfenwick** [comment]
Confirmed -- fixed by #39
